### ISSUE TITLE
dq doesn't compile with *BSD

### ISSUE THREAD

**Issue by pkubaj** [janmojzis/dq#1]
I want to compile dq for FreeBSD and OpenBSD and can't do it.
dq/strtoip.c needs the following patch:
```
--- dq/strtoip.c.orig	2016-12-05 15:29:03 UTC
+++ dq/strtoip.c
@@ -7,6 +7,7 @@ Public domain.
 #include <arpa/inet.h>
 #include "byte.h"
 #include "strtoip.h"
+#include <sys/socket.h>
```
Could you commit it?

**Comment by janmojzis** [comment]
Hello,
fixed here https://github.com/janmojzis/dq/commit/7a5c7f7e7ae1baf9f6980c71b7a5361fbce1c111

Thanks
